Feature functional testing
IGNF/geoportal-access-lib pull request #39
Opened 2017-08-24 09:52 UTC by lowzonenose

Mise en place des tests fonctionnels (en mode bouchon ou sur la clef API)

2017-08-29 16:04 UTC, gcebelieu requested changes
Cette PR embarque tout un tas de modifs issues du merge depuis master (modifs issues d'autres PR). Du coup, j'ai du mal à voir ce qui est réellement modifié dans cette PR par rapport à l'état actuel de master.
Y a moyen de pointer les modifications ?

2017-08-29 17:48 UTC, lowzonenose commented
oui, tous les tests fonctionnels sont dans le répertoire test/spec_functional/ (cf. index-functional.html)

2017-09-11 13:18 UTC, gcebelieu requested changes
Quelques liens en lib/external à changer : 

$ grep -r "lib\/external" test/
test/index-functional.html:            'text'     : '../lib/external/text',
test/index-functional.html:            "log4js"   : "../lib/external/woodman/woodman-amd",
test/index-functional.html:            'promise'  : '../lib/external/es-promise-4.1.0',
test/index-messages-jsonp.html:            "log4js"   : "../lib/external/woodman/woodman-amd",
test/index-messages-jsonp.html:            'promise'  : '../lib/external/promise',
test/index-messages-xhr.html:            "log4js"   : "../lib/external/woodman/woodman-amd",
test/index-messages-xhr.html:            'promise'  : '../lib/external/promise',

2017-09-11 13:18 UTC, gcebelieu commented on test/index-functional.html
> +            'promise'  : '../lib/external/es-promise-4.1.0',
les liens en lib/external ne sont plus valides (lib/external n'existe plus : il faut aller taper dans node_modules désormais ou lib/es6-promise/)

2017-09-11 13:18 UTC, gcebelieu commented on test/index-messages-jsonp.html
> +            'promise'  : '../lib/external/promise',
lib/external n'est plus => utiliser node_modules ou lib/es6-promise

2017-09-11 13:18 UTC, gcebelieu commented on test/index-messages-xhr.html
> +            'promise'  : '../lib/external/promise',
lib/external n'est plus => utiliser node_modules ou lib/es6-promise

2017-09-12 09:31 UTC, gcebelieu requested changes
Ok : j'ai pu faire tourner les tests fonctionnels.

En mode réel (non mock), peux tu enlever l'utilisation du proxy qui ne sert plus à rien et qui fait planter les tests lorsqu'on n'a pas de proxy php installé.

2017-09-12 09:31 UTC, gcebelieu commented on test/index-functional.html
> +            window.proxy = (params.proxy && params.proxy === "true") ? true : false;
Le paramètre proxy défini ici ne semble pas pris en compte dans les tests XHR qui l'utilisent systématiquement en dur (cf. plus loin).
=> Comme le proxy n'est plus nécessaire avec le mode XHR, il faudrait enlever ce paramètre et attaquer directement les services wxs (quand mock == false) sans passer par un proxy quelconque.

2017-09-12 09:31 UTC, gcebelieu commented on test/spec-functional/test.alti.js
> +                        proxyURL: (mock) ? null : "http://localhost/proxy/php/proxy.php?url=",
Pas besoin de proxy même en XHR => à enlever.
(faire de même sur tous les tests XHR qui utilisent le proxy)

2017-09-12 09:37 UTC, lowzonenose commented on test/spec-functional/test.alti.js
> +                        proxyURL: (mock) ? null : "http://localhost/proxy/php/proxy.php?url=",
:white_check_mark:

2017-09-12 09:37 UTC, lowzonenose commented on test/index-functional.html
> +            window.proxy = (params.proxy && params.proxy === "true") ? true : false;
:white_check_mark:

2017-09-12 14:04 UTC, gcebelieu approved these changes
OK, ça marche.

Par contre, il y a pas mal de tests en erreur quand on attaque les services en direct. Il faudra faire une passe dessus pour voir ce qui cloche (à traiter dans une autre PR).

2017-09-12 15:01 UTC, merged