Feature functional testing debug
IGNF/geoportal-access-lib pull request #41
Opened 2017-09-14 15:07 UTC by lowzonenose

Rendre fonctionnel tous les tests **bout en bout** 

- iso 
- route
- :white_check_mark: altimetrie
- :white_check_mark: autocompletion
- :white_check_mark: autoconfiguration
- :white_check_mark: geocodage direct
- :white_check_mark: geocodage inverse

2017-09-15 09:10 UTC, gcebelieu requested changes
C'est beaucoup mieux mais j'ai encore 10 tests en erreur : 

- 3 tests en timeout => il faudrait augmenter le seuil de timeout (5s par exemple) pour voir s'ils passent. S'ils ne passent toujours pas, le problème sera ailleurs

- 4 tests remontent des erreurs sur le nombre attendu de réponses par rapport à celui reçu : sans doute à cause des données =>  Je propose de ne tester que le fait que le nombre de résultat est non nul (NB : un des tests remonte un nombre de résultats nul ; dans ce cas, il faut voir si c'est normal et adapter le test en conséquence)

- le test du service Alti en mode JSONP avec l'API WPS lève une erreur "Script Error..." => il faut voir pourquoi 

- Idem pour le test Isochrones en mode JSONP pour un format de sortie en XML

- Le dernier test (Géocodage direct JSONP pour un format de sortie en XML) lève une erreur : 
Error: done() called multiple times@spec-functional/test.geocode-jsonp.js?bust=1505464207881:126:17

=> voir pourquoi ?

2017-09-15 10:39 UTC, lowzonenose commented
![selection_188](https://user-images.githubusercontent.com/10401006/30478790-d7ea19c0-9a12-11e7-82d3-e07ba4a9b467.png)

![selection_187](https://user-images.githubusercontent.com/10401006/30478796-dcf976e0-9a12-11e7-81c8-5c46220f67bc.png)

![selection_186](https://user-images.githubusercontent.com/10401006/30478815-e60cd75e-9a12-11e7-80f0-528060d37de2.png)

![selection_185](https://user-images.githubusercontent.com/10401006/30478820-ebc4a6cc-9a12-11e7-9268-a37c019c0e65.png)

2017-09-15 10:43 UTC, lowzonenose commented
Quelques test ont été désactivé : 
- Requête sur les services OLS en mode POST (405 Method Not Allowed !?)
- Filtre géométrique de type *circle* sur le service de geocodage inverse (timeout !?)

Toutes les fonctionnalités ne sont pas encore couvertes par les tests...

2017-09-15 13:11 UTC, lowzonenose commented
**(mock)**
![selection_190](https://user-images.githubusercontent.com/10401006/30483581-a916c1f6-9a27-11e7-97f3-c3cbaf4a8124.png)
**(avec un proxy)**
![selection_191](https://user-images.githubusercontent.com/10401006/30483597-b4113172-9a27-11e7-84c9-130fd12f3626.png)
**(sans proxy)**
![selection_192](https://user-images.githubusercontent.com/10401006/30483607-c14beac6-9a27-11e7-9994-41e4a6cb1a01.png)
**(mode direct)**
![selection_193](https://user-images.githubusercontent.com/10401006/30483620-cf4d20b8-9a27-11e7-95bc-892376e9d84a.png)

> échec des services iso et iti car en JSONP, ils ne savent pas répondre en 200 pour lancer leurs exceptions...

2017-09-15 15:04 UTC, gcebelieu commented
Je ne comprends pas pourquoi tu réintègres le proxy dans les tests fonctionnels ?

2017-09-15 15:26 UTC, lowzonenose commented
Problème de Cross Domain d'où l'utilisation d'un proxy...

2017-09-15 15:29 UTC, lowzonenose commented
Problème de Cross domain (origin)...

Le 15 sept. 2017 5:04 PM, "Gilles Cébélieu" <notifications@github.com> a
écrit :

> Je ne comprends pas pourquoi tu réintègres le proxy dans les tests
> fonctionnels ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IGNF/geoportal-access-lib/pull/41#issuecomment-329809032>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJ607ukrIhxY0cReju6SRshH8QjU9T5Sks5sipH7gaJpZM4PXu_E>
> .
>

2017-09-15 15:37 UTC, gcebelieu commented
Normalement, on n'a plus de PB de crossdomain en XHR, donc plus besoin de proxy. 
Dans quels cas, on a encore ces problèmes ?

2017-09-18 09:31 UTC, lowzonenose commented
On a besoin d'un proxy sur les services qui retournent des messages d'erreurs en XML ou qui ne savent pas répondre en 200...

2017-09-18 12:48 UTC, gcebelieu commented
Ce qui me gêne avec l'option proxy==true, c'est que les exemples qui l'utilisent nécessitent l'installation d'un proxy.php qui n'est pas dans les dépôts. Ils ne marcheront donc pas de toutes façons (sauf chez celui qui fera l'effort d'en installer un).

A mon avis : 
- soit on intègre le proxy php dans le dépôt avec les exemples
- soit on n'utilise pas de proxy et on assume que les exemples impactés plantent pour les raisons que tu invoques, quitte à les isoler spécifiquement pour ne pas gêner les exemples qui fonctionnent. 

Ma préférence va sur la deuxième solution : elle met le doigt sur un problème qu'il faut résoudre au niveau des services.

2017-09-18 13:28 UTC, gcebelieu commented
> * soit on n'utilise pas de proxy et on assume que les exemples impactés plantent pour les raisons que tu invoques, quitte à les isoler spécifiquement pour ne pas gêner les exemples qui fonctionnent.
> 
> Ma préférence va sur la deuxième solution : elle met le doigt sur un problème qu'il faut résoudre au niveau des services.

2017-09-27 07:12 UTC, lowzonenose commented
Les tests fonctionnels sur les messages d'erreur des services, _qui ont besoin d'un proxy_, ont été désactivés. 
A nous de voir avec les services sur **pourquoi ont ils besoins d'un proxy pour envoyer des erreurs ?**

2017-09-28 10:09 UTC, gcebelieu approved these changes

2017-09-28 10:10 UTC, merged