ajout de l'option onBeforeParse dans CommonService
IGNF/geoportal-access-lib pull request #43
Opened 2017-10-06 15:07 UTC by sylvainpolletvillard

fix https://github.com/IGNF/geoportal-access-lib/issues/42
ping @lboulanger @gcebelieu 

L'utilisation de cette option se réduit à : 
```js
Gp.Services.getConfig({
	serverUrl: `${URL_PROXY_WXS}/${API_KEY}/autoconf`,
	onBeforeParse: function(xml){
		// remplacement des URL par notre proxy
		return xml.replace(/https:\/\/wxs.ign.fr/g, URL_PROXY_WXS)
	},
	onSuccess: resolve,
	onFailure: reject
});
```

Cela semble en effet être le meilleur compromis à la fois pour IGN et les utilisateurs

2017-10-09 09:15 UTC, lboulanger requested changes
Ça me paraît bien et fonctionnel !
C'est possible de rajouter les commentaires avant de merger, pour la documentation de la fonction onBeforeParse ?

2017-10-09 09:15 UTC, lboulanger commented on src/Services/CommonService.js
> +     *      Permet de modifier la réponse avant parsing si la fonction retourne une String.
Je rajouterais juste des précisions dans les commentaires de la fonction : 
* Cette fonction prend en paramètre la réponse XML telle que renvoyée par le service, sous la forme d'une chaîne de caractères (comportement par défaut).
* Si le paramètre "rawResponse" a été précisé avec la valeur "true", la fonction prend en paramètre un Object JavaScript contenant la réponse XML.

2017-10-09 09:51 UTC, lboulanger commented
Ajout : il faudrait aussi rajouter la documentation de la fonction onBeforeParse dans la classe [Services.js](https://github.com/IGNF/geoportal-access-lib/blob/master/src/Services/Services.js#L22) : c'est à partir de ces commentaires qu'est générée la JSDoc pour la [documentation technique](http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.1/jsdoc/module-Services.html) en ligne. 

Il faut rajouter, pour chacune des fonctions d'appel aux services (getConfig, isoCurve, autoComplete, ... après rawResponse en général) : 
`* @param {Function} [options.onBeforeParse] - Callback function to get service response before parsing (as an unparsed String), in case of a JSONP protocol use (see above). Takes a String as a parameter, except if "rawResponse" parameter is set to true : in this case parameter will be a JavaScript Object. Enables to modify response before parsing : the function needs to return a String that will be parsed as the service response. Ignored when options.protocol is set to 'JSONP' value. Only use if you know what you are doing.`

(n'hésitez pas à reprendre si j'ai fait une erreur)

Merci !

2017-10-09 12:34 UTC, sylvainpolletvillard commented
@lboulanger C'est fait

2017-10-09 12:42 UTC, lboulanger commented
Merci !
Tout me semble OK :+1:

2017-10-09 12:42 UTC, lboulanger approved these changes

2017-10-09 12:46 UTC, merged

2017-10-12 09:20 UTC, lboulanger commented
Bonjour Sylvain,

Tout d'abord, merci encore pour votre contribution au projet :+1: 

Ensuite, en tant que contributeur, pourriez-vous, à l'occasion, jeter un œil à ce tutoriel en cours de rédaction : #40 , qui vise à aider de futurs contributeurs ? 
En nous disant par exemple si vous voyez des oublis voire des erreurs, ou encore si vous avez utilisé d'autres méthodes. Cela nous aiderait beaucoup d'avoir un avis extérieur, et de la part de quelqu'un qui a effectivement contribué.

Merci d'avance !

Bonne journée,
Laurane