Feature docker
IGNF/geoportal-access-lib pull request #69
Opened 2020-03-26 15:27 UTC by lgrd

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

-
-
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2020-03-27 21:02 UTC, lowzonenose requested changes
Dans le répertoire **docker**, j'aurais mis un _shell_ de construction / exécution : 
* build.sh : construire l'image
* run.sh : lancer un container

Le script de **run** devrait s'appuyer sur une variable d'environnement ou le _path_ courant pour mapper le chemin des sources locales avec le container.

Les tests unitaires, e2e et les sources sont en mode _watch_ (reload si modification). 
Les exemples sont ils aussi en mode _watch_ ?

Attention, le container utilise le port par défaut du _nginx_ (8081)... 
Préciser dans le _readme_ qu'il faut stopper son _nginx_ local si on a l'exception suivante : 
> Error starting userland proxy: listen tcp 0.0.0.0:8081: bind: address already in use.

Questions : 
* que doit on faire si il y'a une modification des dépendances _npm_ du _package.json_ ?
(cf. http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/)
* tout fonctionne t il à travers un proxy ?
* si on reconstruit les bundles, mon container est il à jour (ex. tests e2e) ?

Mettre à jour **npm** car il n'est pas compatible avec nodejs : 
```
root@6e888975c60e:/home/docker/geoportal-access-lib# npm doctor 
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.8.0                       Use npm v6.14.4
node -v                             v10.15.2                     Use node v12.16.1
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 1968 tarballs
root@6e888975c60e:/home/docker/geoportal-access-lib# 
```

2020-03-30 15:05 UTC, elias75015 reviewed
Good !

Je rejoins JP sur certains points :

- simplifier les commandes à lancer en passant par exemple par un script sh au nom explicite
- eventuellement avoir un fichier de conf pour mapper le code du projet et les variables de chemin au conteneur docker

Je n'ai pas réussi à faire fonctionner en mode watch (pas de reload à la modification), mais peut-être m'y suis-je mal pris.

2020-04-02 11:12 UTC, lgrd commented
- NPM: mise à jour de NodeJS et NPM en installant depuis les sources. C'est la seule méthode qui a fonctionnée. J'avais tenté une mise à jour via npm itself, une installation depuis le téléchargement des binaires mais cela causait d'autres problèmes. 

- Facilité de builder et lancer le container: mise en place de scripts et de docker-compose. La documentation a été mise à jour pour montrer comment l'utiliser. 

- package.json: pour le moment, si on modifie le package.json, il est nécessaire de le faire directement dans le container ou de commiter puis de rebuilder le container avec l'option "--no-cache". Si on fait le lien entre le fichier de la machine et celui du container, on risque de commiter des changements non désirés. À creuser... 

- si on reconstruit les bundles, les tests e2e sont bien mis à jour.

2020-04-03 23:44 UTC, lowzonenose commented
> * NPM: mise à jour de NodeJS et NPM en installant depuis les sources. C'est la seule méthode qui a fonctionnée. J'avais tenté une mise à jour via npm itself, une installation depuis le téléchargement des binaires mais cela causait d'autres problèmes.

:-1: je ne suis pas fan de la compilation de nodejs...
l'idée serait d'avoir plusieurs petites images (_node_ et _nginx_), et ainsi séparer le fonctionnel (container-access-lib, container-front) qui sera lié dans un _docker-compose_. De plus, lors de la prochaine étape avec les autres projets API, il sera de toute façon utile d'avoir un container front partagé... 

> * Facilité de builder et lancer le container: mise en place de scripts et de docker-compose. La documentation a été mise à jour pour montrer comment l'utiliser.

:+1: 

> * package.json: pour le moment, si on modifie le package.json, il est nécessaire de le faire directement dans le container ou de commiter puis de rebuilder le container avec l'option "--no-cache". Si on fait le lien entre le fichier de la machine et celui du container, on risque de commiter des changements non désirés. À creuser...

:+1: à réfléchir, mais il est déjà certain que les fichiers _package.json_ seront modifiés sur l'ensemble des projets API (upgrade des librairies, maj des dep)

> * si on reconstruit les bundles, les tests e2e sont bien mis à jour.

:+1:

2020-04-14 10:30 UTC, lowzonenose approved these changes

2020-04-16 09:35 UTC, elias75015 approved these changes
OK pour moi aussi :+1:

2020-04-17 07:37 UTC, lgrd commented
est-ce que vous avez vu que j'ai supprimé le package-lock.json ? 

Et que j'ai remis la version de webpack-dev-server à une version qui fonctionnait ?

2020-04-20 12:45 UTC, elias75015 commented
Yes. Je ne vois pas de soucis à ça. Tu confirmes @lowzonenose ?

2020-04-21 11:53 UTC, merged